[package]
name = "memory"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.0"
lazy_static = "1.4.0"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
